// Code generated by "stringer -type=Code -trimprefix="; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Halt-28]
	_ = x[Call-29]
	_ = x[Over-30]
	_ = x[Loop-31]
	_ = x[Break-32]
	_ = x[Pop-33]
	_ = x[Dup-34]
	_ = x[Swap-35]
	_ = x[Ident-36]
	_ = x[Not-37]
	_ = x[And-38]
	_ = x[Or-39]
	_ = x[Xor-40]
	_ = x[Shl-41]
	_ = x[Shr-42]
	_ = x[Add-43]
	_ = x[Sub-44]
	_ = x[Mul-45]
	_ = x[Div-46]
	_ = x[Mod-47]
	_ = x[Eq-48]
	_ = x[Neq-49]
	_ = x[Lt-50]
	_ = x[Le-51]
	_ = x[Gt-52]
	_ = x[Ge-53]
	_ = x[Pipe-54]
	_ = x[Index1-55]
	_ = x[Index2-56]
	_ = x[Field-57]
}

const _Code_name = "HaltCallOverLoopBreakPopDupSwapIdentNotAndOrXorShlShrAddSubMulDivModEqNeqLtLeGtGePipeIndex1Index2Field"

var _Code_index = [...]uint8{0, 4, 8, 12, 16, 21, 24, 27, 31, 36, 39, 42, 44, 47, 50, 53, 56, 59, 62, 65, 68, 70, 73, 75, 77, 79, 81, 85, 91, 97, 102}

func (i Code) String() string {
	i -= 28
	if i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i+28), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
