// Code generated by "stringer -type=Code -trimprefix="; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[Call-1]
	_ = x[Over-2]
	_ = x[Loop-3]
	_ = x[Break-4]
	_ = x[Halt-5]
	_ = x[PushNil-6]
	_ = x[PushNow-7]
	_ = x[PushVar-8]
	_ = x[Pop-9]
	_ = x[Dup-10]
	_ = x[Swap-11]
	_ = x[Not-12]
	_ = x[And-13]
	_ = x[Or-14]
	_ = x[Xor-15]
	_ = x[Shl-16]
	_ = x[Shr-17]
	_ = x[Add-18]
	_ = x[Sub-19]
	_ = x[Mul-20]
	_ = x[Div-21]
	_ = x[Mod-22]
	_ = x[Eq-23]
	_ = x[Neq-24]
	_ = x[Lt-25]
	_ = x[Le-26]
	_ = x[Gt-27]
	_ = x[Ge-28]
	_ = x[Pipe-29]
	_ = x[Index1-30]
	_ = x[Index2-31]
	_ = x[Field-32]
	_ = x[Iter-33]
	_ = x[HashProbe-34]
	_ = x[RBSeek-35]
	_ = x[Limit-36]
	_ = x[Batch-37]
	_ = x[FNV1a-38]
	_ = x[PackKV-39]
	_ = x[PackJSON-40]
	_ = x[UnpackJSON-41]
	_ = x[UnpackKV-42]
	_ = x[From-43]
	_ = x[Store-44]
	_ = x[Upsert-45]
	_ = x[Update-46]
	_ = x[Delete-47]
	_ = x[Txn-48]
}

const _Code_name = "NopCallOverLoopBreakHaltPushNilPushNowPushVarPopDupSwapNotAndOrXorShlShrAddSubMulDivModEqNeqLtLeGtGePipeIndex1Index2FieldIterHashProbeRBSeekLimitBatchFNV1aPackKVPackJSONUnpackJSONUnpackKVFromStoreUpsertUpdateDeleteTxn"

var _Code_index = [...]uint8{0, 3, 7, 11, 15, 20, 24, 31, 38, 45, 48, 51, 55, 58, 61, 63, 66, 69, 72, 75, 78, 81, 84, 87, 89, 92, 94, 96, 98, 100, 104, 110, 116, 121, 125, 134, 140, 145, 150, 155, 161, 169, 179, 187, 191, 196, 202, 208, 214, 217}

func (i Code) String() string {
	if i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
