// Code generated by "stringer -type=Type -trimprefix="; DO NOT EDIT.

package asf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[Nil-1]
	_ = x[U8-2]
	_ = x[U16-3]
	_ = x[U32-4]
	_ = x[U64-5]
	_ = x[U128-6]
	_ = x[U256-7]
	_ = x[I8-8]
	_ = x[I16-9]
	_ = x[I32-10]
	_ = x[I64-11]
	_ = x[I128-12]
	_ = x[I256-13]
	_ = x[F32-14]
	_ = x[F64-15]
	_ = x[Complex64-16]
	_ = x[Complex128-17]
	_ = x[PC-18]
	_ = x[SP-19]
	_ = x[Time-20]
	_ = x[Dur-21]
	_ = x[Bytes-22]
	_ = x[String-23]
	_ = x[Error-24]
	_ = x[IBig-25]
	_ = x[FBig-26]
	_ = x[Type_Count-27]
}

const _Type_name = "NopNilU8U16U32U64U128U256I8I16I32I64I128I256F32F64Complex64Complex128PCSPTimeDurBytesStringErrorIBigFBigType_Count"

var _Type_index = [...]uint8{0, 3, 6, 8, 11, 14, 17, 21, 25, 27, 30, 33, 36, 40, 44, 47, 50, 59, 69, 71, 73, 77, 80, 85, 91, 96, 100, 104, 114}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
