// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TIllegal-0]
	_ = x[TEOF-1]
	_ = x[TIdentifier-2]
	_ = x[TNumber-3]
	_ = x[TFloat-4]
	_ = x[TString-5]
	_ = x[TNull-6]
	_ = x[TTrue-7]
	_ = x[TFalse-8]
	_ = x[TOver-9]
	_ = x[TPlus-10]
	_ = x[TMinus-11]
	_ = x[TStar-12]
	_ = x[TSlash-13]
	_ = x[TPercent-14]
	_ = x[TDot-15]
	_ = x[TComma-16]
	_ = x[TColon-17]
	_ = x[TSemi-18]
	_ = x[TLParen-19]
	_ = x[TRParen-20]
	_ = x[TLBracket-21]
	_ = x[TRBracket-22]
	_ = x[TLBrace-23]
	_ = x[TRBrace-24]
	_ = x[TPipe-25]
	_ = x[TArrow-26]
	_ = x[TEq-27]
	_ = x[TNeq-28]
	_ = x[TLt-29]
	_ = x[TLte-30]
	_ = x[TGt-31]
	_ = x[TGte-32]
	_ = x[TAnd-33]
	_ = x[TOr-34]
}

const _TokenKind_name = "TIllegalTEOFTIdentifierTNumberTFloatTStringTNullTTrueTFalseTOverTPlusTMinusTStarTSlashTPercentTDotTCommaTColonTSemiTLParenTRParenTLBracketTRBracketTLBraceTRBraceTPipeTArrowTEqTNeqTLtTLteTGtTGteTAndTOr"

var _TokenKind_index = [...]uint8{0, 8, 12, 23, 30, 36, 43, 48, 53, 59, 64, 69, 75, 80, 86, 94, 98, 104, 110, 115, 122, 129, 138, 147, 154, 161, 166, 172, 175, 179, 182, 186, 189, 193, 197, 200}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
